### ISSUE TITLE
crashed textures in 1.16.100

### ISSUE THREAD

**Issue by mercadanteus** [wode490390/AntiXray#11]
It crashes water and many other textures, when used in the 1.16.100 version at https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/1.16.100/
Wooden buttons appears everywhere
Below images with and without antixray
![with](https://user-images.githubusercontent.com/24380156/100681647-d7b44480-3339-11eb-929c-650ee66840cb.png)

![sin](https://user-images.githubusercontent.com/24380156/100681637-d4b95400-3339-11eb-8b0f-d5209d89f92a.png)

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/AntiXray/commit/6a07c56f1bb569d692dce4c03271868db891d4e2.
