### ISSUE TITLE
create unexistant blocks

### ISSUE THREAD

**Issue by mercadanteus** [wode490390/AntiXray#9]
Apparently not only change appearence of existing block, but also create randomly new "ghost" blocks of ores in empty spaces, damaging underground structures,
![WhatsApp Image 2020-05-11 at 6 14 53 PM](https://user-images.githubusercontent.com/24380156/81753917-19e76880-9472-11ea-991e-1d7f9cd73d2e.jpeg)

**Comment by wode490390** [comment]
I can't reproduce it

**Comment by mercadanteus** [comment]
Hello and thanks for your answer, you need to be de-opped to notice this issue, I'm attaching 2 pics in a structure a player built at level 41. One is de-opped and the other is opped.

![Minecraft 13_5_2020 11_22_58](https://user-images.githubusercontent.com/24380156/81845797-4f419400-950e-11ea-8f61-35cc6441f425.png)
![Minecraft 13_5_2020 11_20_01](https://user-images.githubusercontent.com/24380156/81845808-523c8480-950e-11ea-8514-53da3a65d98b.png)

**Comment by wode490390** [comment]
Does this still happen with the latest version ([1.2.2](https://github.com/wode490390/AntiXray/releases/download/1.2.2/wodeAntiXray-1.2.2.jar))?

**Comment by mercadanteus** [comment]
No it does not happen with the 1.2.2 but I checked and looks like it does'nt do it's job neither.
